# Generated by Django 3.1.7 on 2021-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_resigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='personal_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='system_returned',
            field=models.BooleanField(default=False),
        ),
    ]
