# Generated by Django 3.1.7 on 2021-03-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('ecpl_tag_name', models.CharField(max_length=30, unique=True)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('hd_type', models.CharField(max_length=30)),
                ('hd_size', models.CharField(max_length=30)),
                ('hd_serial_no', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
