# Generated by Django 3.1.7 on 2021-03-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
