# Generated by Django 3.1.7 on 2021-03-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210302_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='status',
        ),
    ]
