# Generated by Django 3.1.7 on 2021-07-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Newtdata',
        ),
    ]
