# Generated by Django 3.1.7 on 2021-03-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cpu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=50)),
                ('item_serial', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('assigned_by', models.CharField(max_length=50)),
                ('campaign', models.CharField(max_length=100)),
            ],
        ),
    ]
