# Generated by Django 3.1.7 on 2021-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('it_name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('item_serial', models.CharField(max_length=50)),
            ],
        ),
    ]
