# Generated by Django 3.1.7 on 2021-07-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210714_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outgoing',
        ),
        migrations.DeleteModel(
            name='Recovery',
        ),
    ]
