# Generated by Django 3.1.7 on 2021-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicecpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='system_name',
            field=models.CharField(default='saas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='vendor',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
    ]
