# Generated by Django 3.1.7 on 2021-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210714_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('policy_no', models.CharField(max_length=100, null=True)),
                ('it_name', models.CharField(max_length=100, null=True)),
                ('make_model', models.CharField(max_length=100, null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('campaign', models.CharField(max_length=100, null=True)),
                ('system_name', models.CharField(max_length=100, null=True)),
                ('processor', models.CharField(max_length=100, null=True)),
                ('system_serial', models.CharField(max_length=100, null=True)),
                ('hard_disc', models.CharField(max_length=100, null=True)),
                ('hard_disc_serial', models.CharField(max_length=100, null=True)),
                ('hard_disc_size', models.CharField(max_length=100, null=True)),
                ('ram', models.CharField(max_length=100, null=True)),
                ('headset', models.CharField(max_length=100, null=True)),
                ('headset_serial', models.CharField(max_length=100, null=True)),
                ('monitor', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('pc_laptop', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('it_name', models.CharField(max_length=100, null=True)),
                ('policy_no', models.CharField(max_length=100, null=True)),
                ('make_model', models.CharField(max_length=100, null=True)),
                ('system_name', models.CharField(max_length=100, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('campaign', models.CharField(max_length=100, null=True)),
                ('system_serial', models.CharField(max_length=100, null=True)),
                ('processor', models.CharField(max_length=100, null=True)),
                ('hard_disc_serial', models.CharField(max_length=100, null=True)),
                ('ram', models.CharField(max_length=100, null=True)),
                ('headset', models.CharField(max_length=100, null=True)),
                ('headset_serial', models.CharField(max_length=100, null=True)),
                ('monitor', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('pc_laptop', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('emp_status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
