# Generated by Django 3.1.7 on 2021-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_outgoingnew_recoverynew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtdata',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='newtdata',
            name='campaign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='hard_disc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='hard_disc_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='hard_disc_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='headset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='headset_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='it_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='make_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='monitor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='pc_laptop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='policy_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='processor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='ram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='system_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtdata',
            name='system_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outgoingnew',
            name='recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newtdata',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
