# Generated by Django 3.1.7 on 2021-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_returncpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
