# Generated by Django 3.1.7 on 2021-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210714_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingnew',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recoverynew',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
