# Generated by Django 3.1.7 on 2021-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210714_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingnew',
            name='mobile_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
