# Generated by Django 3.1.7 on 2021-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_assigned_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecpu',
            name='service_status',
            field=models.BooleanField(default=False),
        ),
    ]
