# Generated by Django 3.1.7 on 2021-07-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210714_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newtdata',
        ),
        migrations.DeleteModel(
            name='OutgoingNew',
        ),
        migrations.DeleteModel(
            name='RecoveryNew',
        ),
    ]
