# Generated by Django 3.1.7 on 2021-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_servicecpu_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecpu',
            name='service_status',
            field=models.BooleanField(default=True),
        ),
    ]
