# Generated by Django 3.1.7 on 2021-03-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210310_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('ecpl_tag_name', models.CharField(max_length=30, unique=True)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('hd_type', models.CharField(max_length=30)),
                ('hd_size', models.CharField(max_length=30)),
                ('hd_serial_no', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=False)),
                ('out', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
            ],
        ),
    ]
