# Generated by Django 3.1.7 on 2021-03-14 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_desktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
