# Generated by Django 3.1.7 on 2021-03-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210314_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
