# Generated by Django 3.1.7 on 2021-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210314_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='desktop',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
    ]
