# Generated by Django 3.1.7 on 2021-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210314_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='item_name',
            field=models.CharField(default='CPU', max_length=10),
        ),
        migrations.AddField(
            model_name='desktop',
            name='item_name',
            field=models.CharField(default='DESKTOP', max_length=20),
        ),
    ]
