# Generated by Django 3.1.7 on 2021-03-16 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210314_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='MONITOR', max_length=20)),
                ('item_id', models.IntegerField(default=3)),
                ('in_date', models.DateField(default=datetime.date.today)),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('ecpl_tag_name', models.CharField(max_length=30, unique=True)),
                ('model_no', models.IntegerField()),
                ('brand_name', models.CharField(max_length=50)),
                ('screen_size', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='desktop',
            name='item_id',
            field=models.IntegerField(default=2),
        ),
    ]
