# Generated by Django 3.1.7 on 2021-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210316_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
