# Generated by Django 3.1.7 on 2021-03-16 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210316_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='LAPTOP', max_length=20)),
                ('item_id', models.IntegerField(default=4)),
                ('in_date', models.DateField(default=datetime.date.today)),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('ecpl_tag_name', models.CharField(max_length=30, unique=True)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('hd_type', models.CharField(max_length=30)),
                ('hd_size', models.CharField(max_length=30)),
                ('hd_serial_no', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('battery_serial_no', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('out', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
            ],
        ),
    ]
