# Generated by Django 3.1.7 on 2021-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_accesscontroler_biometric_cctv_converters_dvdwriter_externalharddisc_fortiget_keyboard_mouse_pendriv'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecpu',
            name='item',
            field=models.CharField(default='TEST', max_length=50),
        ),
    ]
