# Generated by Django 3.1.7 on 2021-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_servicecpu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecpu',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
