# Generated by Django 3.1.7 on 2021-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210319_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(null=True)),
                ('emp_name', models.CharField(max_length=50, null=True)),
                ('doj', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('process', models.TextField(null=True)),
                ('emp_desi', models.CharField(max_length=50, null=True)),
                ('personal_no', models.IntegerField(null=True)),
                ('emergency_no', models.IntegerField(null=True)),
                ('aadhar_no', models.CharField(max_length=50, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('no_of_systems', models.IntegerField(null=True)),
                ('pc_or_lap', models.CharField(max_length=50, null=True)),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('serial', models.CharField(max_length=50, null=True)),
                ('ram', models.CharField(max_length=50, null=True)),
                ('hard_disc', models.CharField(max_length=50, null=True)),
                ('system_remarks', models.TextField(null=True)),
                ('inch_18', models.IntegerField(null=True)),
                ('inch_19', models.IntegerField(null=True)),
                ('inch_20', models.IntegerField(null=True)),
                ('inch_24', models.IntegerField(null=True)),
                ('monitor_remarks', models.TextField(null=True)),
                ('head_company', models.CharField(max_length=50, null=True)),
                ('head_own', models.CharField(max_length=10, null=True)),
                ('head_remarks', models.TextField(null=True)),
                ('keyboard', models.CharField(max_length=10, null=True)),
                ('mouse', models.CharField(max_length=10, null=True)),
                ('webcam', models.CharField(max_length=10, null=True)),
                ('other_remarks', models.TextField(null=True)),
                ('sophos', models.CharField(max_length=10, null=True)),
                ('connectwise', models.CharField(max_length=10, null=True)),
                ('vpn', models.CharField(max_length=10, null=True)),
                ('vpn_id', models.CharField(max_length=10, null=True)),
                ('call_date', models.DateField(null=True)),
                ('called_by', models.CharField(max_length=50, null=True)),
                ('called_by_id', models.IntegerField(null=True)),
                ('emp_remarks', models.TextField(null=True)),
                ('data_collected', models.BooleanField(default=False)),
                ('agent_remarks', models.TextField(null=True)),
            ],
        ),
    ]
