# Generated by Django 3.1.7 on 2021-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='call_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='doj',
            field=models.DateTimeField(null=True),
        ),
    ]
