# Generated by Django 3.1.7 on 2021-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210519_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='personal_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
