# Generated by Django 3.1.7 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210519_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='number_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_error_remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='shift',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='shift_error',
            field=models.BooleanField(default=False),
        ),
    ]
